### ISSUE TITLE
加载插件中的 so文件 崩溃

### ISSUE THREAD

**Issue by cyoyochoo** [wyouflf/xPlugin#4]
```
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/org.xplugin.demo.app/app_xpl_modules/org.xplugin.demo.module2/1/libares.so" is 32-bit instead of 64-bit
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1657)
```
但是我单独安装这个插件APK是可以运行的，把他编成插件使用就报上面这个错误，巨佬有办法解决吗？

**Comment by wyouflf** [comment]
你的可以给我一个用于调试的demo吗, 我这边demo里的so库加载正常.

**Comment by cyoyochoo** [comment]
> 你的可以给我一个用于调试的demo吗, 我这边demo里的so库加载正常.

代码在： https://gitee.com/yoyochoo/xPlugin
fork的你的项目，我在module2加入了我们的一个功能，但是崩溃了，谢谢了
您方便加个好友吗？我的微信号：yoyochoo
